sudo: required
dist: trusty

services:
  - docker

env:
  ENV=travis

install:
  # Inspect some variables
  - pwd
  - ls -lash

  # Node
  - npm -v
  - node -v

  # Go
  - eval "$(gimme 1.9.4)"
  - go version
  - go env
  - mkdir -p /home/travis/gopath/src/github.com/bobinette
  - ln -s /home/travis/build/bobinette/tonight /home/travis/gopath/src/github.com/bobinette/tonight

  # Install mysql 5.7 via docker
  - .travis/install_mysql.sh

  # Install Go dependencies
  - go get -u -v github.com/kardianos/govendor/...
  - cd /home/travis/gopath/src/github.com/bobinette/tonight/tonight
  - govendor sync -v
  - cd /home/travis/build/bobinette/tonight

  # Install front dependencies
  - cd /home/travis/build/bobinette/tonight/app
  - npm install
  - cd /home/travis/build/bobinette/tonight

  # Wait for mysql to be up
  - ".travis/wait_mysql.sh"
  - git clone https://github.com/mbucc/shmig.git ./mysql/shmig
  - |
    ./mysql/shmig/shmig \
      -t mysql \
      -H 127.0.0.1 \
      -P 3307 \
      -l tonight \
      -p tonight \
      -d tonight_test \
      -m ./tonight/mysql/migrations \
      up

script:
  # Go
  - >
    cd /home/travis/gopath/src/github.com/bobinette/tonight/tonight &&
    go test ./... -v &&
    cd /home/travis/build/bobinette/tonight

  # JS
  - >
    cd /home/travis/build/bobinette/tonight/app anpm run test &&
    npm run test &&
    cd /home/travis/build/bobinette/tonight

before_deploy:
  # Create bin directory
  - mkdir bin

  # Build web server linux
  - >
    cd /home/travis/gopath/src/github.com/bobinette/tonight/tonight &&
    GOOS=linux GOARCH=amd64 go build -o ../bin/tonight ./cmd/main.go &&
    cd /home/travis/build/bobinette/tonight

  # Build front
  - >
    cd /home/travis/build/bobinette/tonight/app &&
    npm run build &&
    cd /home/travis/build/bobinette/tonight

  # Add the shmig migration files to the archive
  - >
    cd /home/travis/gopath/src/github.com/bobinette/tonight/tonight &&
    cp -r mysql/migrations ../bin/migrations &&
    cd /home/travis/build/bobinette/tonight

  # bundle it all
  - mkdir bin/bleve
  - cp tonight/bleve/mapping.json bin/bleve/mapping.json
  - cd bin
  - tar -zcvf ../tonight-linux.tar.gz .
  - cd /home/travis/build/bobinette/tonight

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BQBUdNUPuiIMgXhvhhNOUBqmRLycsUGMo1QX71pgWGbA63Q8MqmETS6PsshXpheCzKKCu1sRZhmr2p8S4JMcsuiqwTRkCGlQ5HpqpoOx71/bPMnFSba9x6jNbjZQ3D0nXBaWU8NOQzcZzMPWbnmuo5CGLRHPeC5FhDPWblKQ6kxFczFhA9HKLEVs4WZ74NmXSJg6OLgYbIjqLhQGmZlUMP2uYyBidPH8Phrg8slZu0tOu2+5Dgs9+/YZCVa6U5gojMDHsaMgqNqjgffpK2dQqA9Eu9n2174Jp7zC175yGXxHdCSy2/ngYY1+azXKCeSRoDJ0ANM4d619EFH2vnca8r48uoBfJrEIVSC9LgIFTUmFHvGq5XC5sU27qs56XGeHxD/JP4zIUfmy5dzm2XC6c2WUpThIUpyDKn5PIILQIKvXHU5ZgX9TUlfz0NP1ipIVrXbBgbyOF9ZDbdOZSbcvAqFijeOhf/Z8RTxSLcGg2V6G+2t4TXmBWlHKz8ON+0ThOxxcA66gF8ujLsA4al/DAMRjL1g7uKy4meGOGqyhs2iMaKs0E7JX/y8+LUusUmjeFz04b9r3Z7np67N0VBg9UlnYucImV2DcoklqIDXrxeId4/d40Wr58Wwf9DgLuQP7yhCzQOJEDbL+u6cloqOleaGebaQr0d1xeWqVUi346bA=
  file:
    - tonight-linux.tar.gz
  on:
    tags: true
    repo: bobinette/tonight

notifications:
  email:
    on_success: change
    on_failure: change

# Build only the master branch. The PRs will still be built
branches:
  only:
    - master
    # Regex for tags, needed for releases
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
