version: "3.4"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'

  tonight:
    image: tonight:latest
    ports:
      - 9090:9090
    environment:
      MYSQL_HOST: mysql

volumes:
  db-data:

